app = "simple-email-assistant"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "state"
  destination = "/app/state"

[env]
  HEALTH_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    method = "GET"
    path = "/health"
